name: guardia
description: A new Flutter project for an emergency call application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0" # Ensure the Dart SDK is compatible

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.0.0 # Use the latest version available

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


